### PR TITLE
[Delivers #136223203] Implement eslint config

### PR DESCRIPTION
**Pull request by richcsmith**
### Summary:
This is a fork of [Facebook's `create-react-app`](https://github.com/facebookincubator/create-react-app). This is done so that we can still rebase further changes to `create-react-app`, while affording us the ability to implement any overrides necessary for our specific workflow. The changes in this PR introduce Airbnb's linter, with a few custom rule overrides (as discussed with @beausmith).

### Blocker for:
This PR is currently a blocker for: https://github.com/omniprojects/omni-web-app/pull/321.

### CODE REVIEW

**Review by azoff — APPROVED** [review]
LGTM- though if you're going to this length, why not just eject? Now we have to maintain two projects; seems to take away from there benefit of the library. To be clear, I'm fine with it- just seems like it might be harder

**Comment by richcsmith** [comment]
@azoff I suggested ejecting, but @beausmith was against it. Thus, this is the alternative.

**Comment by azoff** [comment]
Roger that.

**Comment by beausmith** [comment]
@azoff - this can be used as the base for other React apps at Omni. And helps constrain our efforts between foundation-specific and app-specific functionality.

**Comment by beausmith** [comment]
LGTM!

**Review by beausmith — COMMENTED** [review]
LGTM

**Review by beausmith — APPROVED** [review]

**Pull request merged**
